name: hello-world
on: 
  push
    branches:
      - dev
      - qa
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step-1
        if: endsWith(github.ref, '/dev')
        run: echo "Hello world it is dev branch!"
      - name: my-step-2
        if: endsWith(github.ref, '/qa')
        run: echo "Hello world it is qa branch!"
